---
- name: Install pip on Ubuntu 22
  hosts: localhost
  remote_user: ubuntu
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install python3-pip package
      apt:
        name: python3-pip
        state: present

- name: Include the konstruktoid.hardening role
  hosts: localhost
  remote_user: ubuntu
  become: yes
  any_errors_fatal: true
  tasks:
    - name: Include role
      ansible.builtin.include_role:
        # name: konstruktoid.hardening
        name: ansible-role
      vars:
        block_blacklisted: true
        #sshd_admin_net:
        #  - 0.0.0.0/0
        #  - 34.125.92.92/24
        suid_sgid_permissions: false
- name: Debug facts
  hosts: localhost
  remote_user: ubuntu
  become: yes
  any_errors_fatal: true
  tasks:
    - name: Include debug tasks
      ansible.builtin.include_tasks: debug_facts.yml

- name: Debug facts
  hosts: localhost
  remote_user: ubuntu
  become: yes
  any_errors_fatal: true
  tasks:
    - name: Include debug tasks
      ansible.builtin.include_tasks: my-playbook.yam


my-playbook.yaml
