---
- name: Ensure Cron Logging is Enabled
  hosts: localhost
  remote_user: ubuntu
  become: true
  tasks:
    - name: Check if cron logging is enabled
      command: grep -q '^cron\.\*' /etc/rsyslog.d/50-default.conf
      register: cron_logging_enabled
      changed_when: false
      failed_when: false

    - name: Enable cron logging
      lineinfile:
        path: /etc/rsyslog.d/50-default.conf
        line: 'cron.* /var/log/cron.log'
        insertafter: EOF
      when: cron_logging_enabled.rc != 0
      notify:
        - restart rsyslog

  handlers:
    - name: restart rsyslog
      service:
        name: rsyslog
        state: restarted
