---
- name: Ensure minclass is set in /etc/security/pwquality.conf
  hosts: localhost
  remote_user: ubuntu
  become: true
  tasks:
    - name: Check if pwquality.conf exists
      stat:
        path: /etc/security/pwquality.conf
      register: pwquality_conf_stat

    - name: Create pwquality.conf if not present
      copy:
        content: |
          minclass = 3
        dest: /etc/security/pwquality.conf
        owner: root
        group: root
        mode: '0644'
      when: not pwquality_conf_stat.stat.exists

    - name: Update pwquality.conf if minclass is not set
      lineinfile:
        path: /etc/security/pwquality.conf
        regex: '^minclass ='
        line: 'minclass = 3'
      when: pwquality_conf_stat.stat.exists
