---
- name: Ensure nss-resolve is present in /etc/nsswitch.conf
  hosts: localhost
  remote_user: ubuntu
  become: true
  tasks:
    - name: Check current smtpd_banner value
      shell: postconf -h smtpd_banner
      register: postconf_result
      changed_when: false
      failed_when: false

    - name: Set smtpd_banner to the desired value
      command: postconf -e 'smtpd_banner = $myhostname ESMTP'
      when: "'$myhostname ESMTP' != postconf_result.stdout.strip()"

    - name: Display result
      debug:
        msg: "smtpd_banner is {{ 'set correctly' if ('$myhostname ESMTP' == postconf_result.stdout.strip()) else 'not set correctly' }}"
